### ISSUE TITLE
1.1.8版本请求author数据问题

### ISSUE THREAD

**Issue by lizepy** [dchijack/wp-mini-program#1]
更新后/wp-json/wp/v2/posts请求到的author数据只有作者的ID

1.1.7版本可以获取到头像昵称和id。

1.1.8版本只能请求到一个id

**Comment by dchijack** [comment]
主要是兼容古腾堡编辑器，对 API rest 的数据输出做了判断请求。只有小程序客户端请求才显示其他信息。
